export const SET_ACTIVE_MENU_ITEM = 'SET_ACTIVE_MENU_ITEM';

export const RECEIVE_FACEBOOK_DATA = 'RECEIVE_FACEBOOK_DATA';
export const WIPE_FACEBOOK_DATA = 'WIPE_FACEBOOK_DATA';

export const REQUEST_NEWS = 'REQUEST_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';

export const REQUEST_IMAGE_LIMIT = 'REQUEST_IMAGE_LIMIT';
export const RECEIVE_IMAGE_LIMIT = 'RECEIVE_IMAGE_LIMIT';

export const REQUEST_MODELS = 'REQUEST_MODELS';
export const RECEIVE_MODELS = 'RECEIVE_MODELS';
export const RECEIVE_SELECTED_MODEL = 'RECEIVE_SELECTED_MODEL';

export const REQUEST_BUILD_TYPES = 'REQUEST_BUILD_TYPES';
export const RECEIVE_BUILD_TYPES = 'RECEIVE_BUILD_TYPES';

export const REQUEST_MANUFACTURERS = 'REQUEST_MANUFACTURERS';
export const RECEIVE_MANUFACTURERS = 'RECEIVE_MANUFACTURERS';

export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS';
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS';
export const RECEIVE_SELECTED_LOCATION = 'RECEIVE_SELECTED_LOCATION';

export const REQUEST_COLORS = 'REQUEST_COLORS';
export const RECEIVE_COLORS = 'RECEIVE_COLORS';

export const GENERATE_YEARS = 'GENERATE_YEARS';
export const YEARS_POPULATED = 'YEARS_POPULATED';

export const REQUEST_SELLER_TYPES = 'REQUEST_SELLER_TYPES';
export const RECEIVE_SELLER_TYPES = 'RECEIVE_SELLER_TYPES';
export const RECEIVE_SELECTED_SELLER_TYPE = 'RECEIVE_SELECTED_SELLER_TYPE';

export const REQUEST_CAR_TYPES = 'REQUEST_CAR_TYPES';
export const RECEIVE_CAR_TYPES = 'RECEIVE_CAR_TYPES';
export const RECEIVE_SELECTED_CAR_TYPE = 'RECEIVE_SELECTED_CAR_TYPE';

export const REQUEST_PRICES = 'REQUEST_PRICES';
export const RECEIVE_PRICES = 'RECEIVE_PRICES';
export const RECEIVE_SELECTED_PRICE = 'RECEIVE_SELECTED_PRICE';

export const REQUEST_CAR_BY_LOT_NUMBER = 'REQUEST_CAR_BY_LOT_NUMBER';
export const RECEIVE_CAR_BY_LOT_NUMBER = 'RECEIVE_CAR_BY_LOT_NUMBER';

export const REQUEST_CARS = 'REQUEST_CARS';
export const REQUEST_PREMIUM_CARS = 'REQUEST_PREMIUM_CARS';
export const REQUEST_PREMIUM_DEALER_CARS = 'REQUEST_PREMIUM_DEALER_CARS';
export const REQUEST_FEATURE_CARS = 'REQUEST_FEATURE_CARS';

export const RECEIVE_CARS = 'RECEIVE_CARS';
export const RECEIVE_PREMIUM_CARS = 'RECEIVE_PREMIUM_CARS';
export const RECEIVE_PREMIUM_DEALER_CARS = 'RECEIVE_PREMIUM_DEALER_CARS';
export const RECEIVE_FEATURE_CARS = 'RECEIVE_FEATURE_CARS';

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const FAILED_USER_LOGIN = 'FAILED_USER_LOGIN';
export const REQUEST_USER_LOGOUT = 'REQUEST_USER_LOGOUT';
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_INFO_UPDATE = 'USER_INFO_UPDATE';

export const SET_OWNER_OPT_ID = 'SET_OWNER_OPT_ID';

export const SET_FUEL_TYPE_OPT_ID = 'SET_FUEL_TYPE_OPT_ID';

export const SET_LICENCE_STATUS_OPT_ID = 'SET_LICENCE_STATUS_OPT_ID';

export const REQUEST_MARKETPLACE_ITEMS = 'REQUEST_MARKETPLACT_ITEMS';
export const RECEIVE_MARKETPLACE_ITEMS = 'RECEIVE_MARKETPLACE_ITEMS';

export const REQUEST_MARKETPLACE_ITEMS_BY_SHOP = 'REQUEST_MARKETPLACT_ITEMS_BY_SHOP';
export const RECEIVE_MARKETPLACE_ITEMS_BY_SHOP = 'RECEIVE_MARKETPLACE_ITEMS_BY_SHOP';

export const REQUEST_MARKETPLACE_ITEMS_BY_SHOP_ID = 'REQUEST_MARKETPLACT_ITEMS_BY_SHOP_ID';
export const RECEIVE_MARKETPLACE_ITEMS_BY_SHOP_ID = 'RECEIVE_MARKETPLACE_ITEMS_BY_SHOP_ID';

export const REQUEST_MARKETPLACE_ITEMS_BY_CATEGORY = 'REQUEST_MARKETPLACT_ITEMS_BY_CATEGORY';
export const RECEIVE_MARKETPLACE_ITEMS_BY_CATEGORY = 'RECEIVE_MARKETPLACE_ITEMS_BY_CATEGORY';

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_ENTRIES = 'REQUEST_ENTRIES';
export const RECEIVE_ENTRIES = 'RECEIVE_ENTRIES';

export const REQUEST_NOTIFICATIONS = 'REQUEST_ENTRIES';
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';

export const SET_LOCALE = 'SET_LOCALE';
export const SET_OPTIONS = 'SET_OPTIONS';

export const SET_POPUP_LAST_SHOWN_TIME = 'SET_POPUP_LAST_SHOWN_TIME';

export const UPDATE_USER_ROLE = 'UPDATE_USER_ROLE';

export const SAVE_CAMPAIGN_LISTING = 'SAVE_CAMPAIGN_LISTING';
export const REMOVE_CAMPAIGN_LISTING = 'REMOVE_CAMPAIGN_LISTING';

export const ADD_CARS_COMPARISON = 'ADD_CARS_COMPARISON';
export const REMOVE_CARS_COMPARISON = 'REMOVE_CARS_COMPARISON';

export const REQUEST_CLEAR_CARS_COMPARISON = 'REQUEST_CLEAR_CARS_COMPARISON';

export const ADD_WISHLIST_CARS = 'ADD_WISHlIST_CARS';
export const UPDATE_WISHLIST_CARS = 'UPDATE_WISHLIST_CARS';

export const REQUEST_CURRENT_CAR = 'REQUEST_CURRENT_CAR';
export const ADD_CURRENT_CAR_LISTING = 'ADD_CURRENT_CAR_LISTING';

export const SHOW_REF_APP = 'SHOW_REF_APP';
export const HIDE_REF_APP = 'HIDE_REF_APP';

export const ADD_SEARCH_STATE_MODEL = 'ADD_SEARCH_STATE_MODEL';
export const REMOVE_SEARCH_STATE_MODEL = 'REMOVE_SEARCH_STATE_MODEL';

export const ADD_FILTER_QUERY = 'ADD_FILTER_QUERY';
export const REMOVE_FILTER_QUERY = 'REMOVE_FILTER_QUERY';

export const SHOW_MOBILE_APP = 'SHOW_MOBILE_APP';
export const HIDE_MOBILE_APP = 'HIDE_MOBILE_APP';

export const UPDATE_USER_NOTIFICATION = "UPDATE_USER_NOTIFICATION";
export const RECEIVE_USER_NOTIFICATION = "RECEIVE_USER_NOTIFICATION";

export const UPDATE_USER_NOTIFICATION_LOGOUT = "UPDATE_USER_NOTIFICATION_LOGOUT";

export const TOGGLE_NAV_BAR = 'TOGGLE_NAV_BAR';
